# Generated by Django 4.1.7 on 2023-08-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order_rename_oderitem_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_adder',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='cyti',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
